- Created Thread which extends Thread class
NikolayFatkullin/Multithreading pull request #1
Opened 2021-02-22 12:44 UTC by NikolayFatkullin

- Created Thread which implements Runnable interface

2021-02-22 16:29 UTC, Fedich09 requested changes

2021-02-22 16:29 UTC, Fedich09 commented on src/main/java/CustomThreadImplementingRunnable.java
> +    private int value;
```suggestion
    private int value;
```
Let’s create class Counter with field and methods. Use one object of counter in two threads, not separate for each thread.

2021-02-22 16:29 UTC, Fedich09 commented on src/main/java/CustomThreadExtendingThreadClass.java
> +    private int value;
```suggestion
    private int value;
```
Let’s create class Counter with field and methods. Use one object of counter in two threads, not separate for each thread.

2021-02-22 17:12 UTC, Fedich09 approved these changes

2021-02-23 07:40 UTC, Sofasmile requested changes

2021-02-23 07:40 UTC, Sofasmile commented on src/main/java/Counter.java
> +    private static int count;
чому змінна статична? і методи також?

2021-02-23 07:40 UTC, Sofasmile commented on src/main/java/CustomThreadImplementingRunnable.java
> +        for (int i = 0; i <= 100; i++) {
в умові завдання написано що потрібно інкрементувати Counter до 100, в даному випадку ми робимо так, щоб кожен поток виконав 100 разів операцю increment, проте значення Counter беде не 100, а більше.
давай трохи змінимо умову циклу

2021-02-23 09:50 UTC, Sofasmile approved these changes

2021-02-23 21:44 UTC, merged